module Helpers_PACKET_SPACE_CONNECTION

open Pulse
open Pulse.Lib.C
#lang-pulse

module C = Struct_connection
module PS = Struct_packet_space
module U32 = Typedef_uint32_t
module R = Pulse.Lib.Reference
module T = Pulse.Lib.Trade
module CR = Pulse.Lib.C.CoreRef

// A connection owner retains both separately allocated objects. The packet-space
// back-pointer is a core_ref, so CoreRef.core_to_ref recovers the connection
// allocation address. The selected connection.packet_space slot is ordinary and
// therefore uses a direct equality to ps.
[@@pulse_unfold]
let connection_owner
  (ps: ref PS.struct_packet_space)
  (ps_v: PS.struct_packet_space)
  (conn_v: C.struct_connection)
  : slprop =
  R.pts_to ps ps_v
  ** R.pts_to
       (CR.core_to_ref C.struct_connection
          ps_v.PS.struct_packet_space__connection)
       conn_v
  ** pure (conn_v.C.struct_connection__packet_space == ps)

[@@pulse_unfold]
let connection_owner_exists (ps: ref PS.struct_packet_space) : slprop =
  exists* (ps_v: PS.struct_packet_space) (conn_v: C.struct_connection).
    connection_owner ps ps_v conn_v

// The separate capability trades raw packet-space ownership for the complete
// connection owner. Its conclusion also contains the packet-space allocation,
// so spending the trade cannot lose that allocation.
let packet_space_to_connection
  (ps: ref PS.struct_packet_space)
  (ps_v: PS.struct_packet_space)
  (conn_v: C.struct_connection)
  : slprop =
  T.trade
    (R.pts_to ps ps_v)
    (connection_owner ps ps_v conn_v)

// An owner alone may create the separate trade needed by the direct update
// interface. It leaves the raw packet-space resource alongside the capability.
ghost fn create_packet_space_trade (ps: ref PS.struct_packet_space)
  requires connection_owner_exists ps
  ensures exists* (ps_v: PS.struct_packet_space) (conn_v: C.struct_connection).
    R.pts_to ps ps_v ** packet_space_to_connection ps ps_v conn_v
{
  unfold (connection_owner_exists ps);
  with ps_v conn_v. assert (connection_owner ps (reveal ps_v) (reveal conn_v));
  unfold (connection_owner ps (reveal ps_v) (reveal conn_v));
  T.intro_trade
    (R.pts_to ps (reveal ps_v))
    (connection_owner ps (reveal ps_v) (reveal conn_v))
    (R.pts_to
       (CR.core_to_ref C.struct_connection
          (reveal ps_v).PS.struct_packet_space__connection)
       (reveal conn_v)
     ** pure ((reveal conn_v).C.struct_connection__packet_space == ps)) fn _ {
      fold (connection_owner ps (reveal ps_v) (reveal conn_v))
    };
  fold (packet_space_to_connection ps (reveal ps_v) (reveal conn_v));
  introduce exists* (ps_v_out: PS.struct_packet_space)
    (conn_v_out: C.struct_connection).
      R.pts_to ps ps_v_out ** packet_space_to_connection ps ps_v_out conn_v_out
    with (reveal ps_v) (reveal conn_v)
}

// This tiny consumer composes PAL's consumed packet-space precondition with
// the separately quantified trade, then spends exactly those two resources.
// Match the trade first so its packet-space view is fixed before matching the
// consumed raw ownership generated by PAL.
ghost fn consume_packet_space_trade (ps: ref PS.struct_packet_space)
  requires exists* (ps_v: PS.struct_packet_space) (conn_v: C.struct_connection).
    packet_space_to_connection ps ps_v conn_v ** R.pts_to ps ps_v
  ensures exists* (ps_v: PS.struct_packet_space) (conn_v: C.struct_connection).
    connection_owner ps ps_v conn_v
{
  with ps_v conn_v. assert (
    packet_space_to_connection ps (reveal ps_v) (reveal conn_v)
    ** R.pts_to ps (reveal ps_v));
  unfold (packet_space_to_connection ps (reveal ps_v) (reveal conn_v));
  T.elim_trade
    (R.pts_to ps (reveal ps_v))
    (connection_owner ps (reveal ps_v) (reveal conn_v));
  introduce exists* (ps_v_out: PS.struct_packet_space)
    (conn_v_out: C.struct_connection).
      connection_owner ps ps_v_out conn_v_out
    with (reveal ps_v) (reveal conn_v)
}
