module Pulse.Lib.C.Palow.Encoding

(* ---------------------------------------------------------------------------
   Object representations of unsigned integers.

   This is the concrete witness that Palow's `*_repr` relations can be
   *defined* rather than axiomatized. `encode bo n p x` is the `n`-byte
   representation of `x` in byte order `bo`, with every byte tagged with
   provenance `p`; `decode bo` is its partial inverse, undefined (`None`) when
   any covered byte is uninitialized.

   Nothing here fixes the order. `byte_at p x k` is the byte of *significance*
   `k` (0 is the least significant), and the order decides only which
   significance is stored at which offset, `significance bo n i`. Every lemma
   is proved for both orders, so the library built on this is order-generic: a
   representation is stated at `Pulse.Lib.C.Palow.Target.byte_order`, which is
   abstract to the library and generated by `pal` from the target it
   translated for. A proof that needs the concrete order asks for it through
   the generated `Pulse.Lib.C.Palow.TargetFacts` -- see `palow.md`.
   --------------------------------------------------------------------------- *)

open Pulse.Lib.C.Palow.Bytes
module Seq = FStar.Seq
module U8 = FStar.UInt8
module M = FStar.Math.Lemmas

type byte_order = | LittleEndian | BigEndian

(* The significance of the byte stored at offset `i` of an `n`-byte object. *)
let significance (bo: byte_order) (n: nat) (i: nat { i < n }) : k:nat { k < n } =
  match bo with
  | LittleEndian -> i
  | BigEndian -> n - 1 - i

let byte_at (p: prov) (x: nat) (k: nat) : byte =
  { value = Some (U8.uint_to_t ((x / pow2 (8 * k)) % 256)); prov = p }

let encode (bo: byte_order) (n: nat) (p: prov) (x: nat) : b:bytes { len b == n } =
  Seq.init n (fun (i: nat { i < n }) -> byte_at p x (significance bo n i))

let encode_index (bo: byte_order) (n: nat) (p: prov) (x: nat) (i: nat)
  : Lemma (requires i < n)
          (ensures  get (encode bo n p x) i == byte_at p x (significance bo n i))
          [SMTPat (get (encode bo n p x) i)]
  = ()

let encode_has_prov (bo: byte_order) (n: nat) (p: prov) (x: nat)
  : Lemma (has_prov p (encode bo n p x) /\ initialized (encode bo n p x))
          [SMTPat (encode bo n p x)]
  = ()

(* ---------------------------------------------------------------------------
   Reversal: a big-endian encoding is a reversed little-endian one, which is
   how every big-endian fact below is reduced to the little-endian one. *)

let rev (b: bytes) : b':bytes { len b' == len b } =
  Seq.init (len b) (fun (i: nat { i < len b }) -> get b (len b - 1 - i))

let rev_index (b: bytes) (i: nat)
  : Lemma (requires i < len b)
          (ensures  get (rev b) i == get b (len b - 1 - i))
          [SMTPat (get (rev b) i)]
  = ()

let rev_involutive (b: bytes) : Lemma (rev (rev b) == b) =
  bytes_ext (rev (rev b)) b

let rev_initialized (p: prov) (b: bytes)
  : Lemma (requires initialized b /\ has_prov p b)
          (ensures  initialized (rev b) /\ has_prov p (rev b))
  = ()

let encode_rev (n: nat) (p: prov) (x: nat)
  : Lemma (rev (encode BigEndian n p x) == encode LittleEndian n p x)
  = bytes_ext (rev (encode BigEndian n p x)) (encode LittleEndian n p x)

let encode_be_as_rev (n: nat) (p: prov) (x: nat)
  : Lemma (encode BigEndian n p x == rev (encode LittleEndian n p x))
  = encode_rev n p x;
    rev_involutive (encode BigEndian n p x)

(* A one-byte object has no byte order: a `char` view of a byte is the same on
   every target. *)
let encode_one (bo: byte_order) (p: prov) (x: nat)
  : Lemma (encode bo 1 p x == encode LittleEndian 1 p x)
  = bytes_ext (encode bo 1 p x) (encode LittleEndian 1 p x)

(* ---------------------------------------------------------------------------
   Decoding. `decode_le` reads the least significant byte first; a big-endian
   range is decoded by reversing it. *)

let rec decode_le (b: bytes) : Tot (option nat) (decreases (len b)) =
  if len b = 0 then Some 0
  else match (get b 0).value with
       | None -> None
       | Some v ->
         (match decode_le (slice b 1 (len b)) with
          | None -> None
          | Some r -> Some (U8.v v + 256 * r))

let decode (bo: byte_order) (b: bytes) : option nat =
  match bo with
  | LittleEndian -> decode_le b
  | BigEndian -> decode_le (rev b)

(* Dropping the first byte of an `n`-byte little-endian encoding of `x` leaves
   the `(n-1)`-byte encoding of `x / 256`: the induction step for
   `decode_le_encode`. *)
#push-options "--z3rlimit 30"
let encode_tail (n: nat { n > 0 }) (p: prov) (x: nat)
  : Lemma (slice (encode LittleEndian n p x) 1 n == encode LittleEndian (n - 1) p (x / 256))
  = let lhs = slice (encode LittleEndian n p x) 1 n in
    let rhs = encode LittleEndian (n - 1) p (x / 256) in
    assert_norm (pow2 8 == 256);
    let aux (i: nat { i < n - 1 }) : Lemma (get lhs i == get rhs i) =
      Seq.lemma_index_slice (encode LittleEndian n p x) 1 n i;
      assert (get lhs i == byte_at p x (i + 1));
      M.pow2_plus 8 (8 * i);
      assert (pow2 (8 * (i + 1)) == 256 * pow2 (8 * i));
      M.division_multiplication_lemma x 256 (pow2 (8 * i));
      assert (x / pow2 (8 * (i + 1)) == (x / 256) / pow2 (8 * i))
    in
    Classical.forall_intro aux;
    bytes_ext lhs rhs
#pop-options

(* The first byte of a little-endian encoding. It is `byte_at p x 0`, and
   `pow2 (8 * 0)` is `1`, but saying so inside `decode_le_encode` costs a query
   with the induction hypothesis and the whole `encode`/`decode`
   axiomatization in context. Here there is nothing to search. *)
let encode_head (n: nat { n > 0 }) (p: prov) (x: nat)
  : Lemma ((get (encode LittleEndian n p x) 0).value == Some (U8.uint_to_t (x % 256)))
  = assert_norm (pow2 (8 * 0) == 1)

(* The arithmetic core of `decode_le_encode`, with no bytes in sight: splitting
   a number modulo `256 * m` into its low byte and the rest. Stated over plain
   `nat`s because that is what it is about, and because the solver was
   previously proving it in a context full of sequences and quantified
   pointwise predicates, where the nonlinear steps below turn into a search. *)
#push-options "--z3rlimit 30"
let mod_split (x: nat) (m: pos)
  : Lemma (x % (256 * m) == x % 256 + 256 * ((x / 256) % m))
  = M.modulo_division_lemma x 256 m;
    M.modulo_modulo_lemma x 256 m;
    M.euclidean_division_definition (x % (256 * m)) 256
#pop-options

(* `pow2 (8 * n) == 256 * pow2 (8 * (n - 1))`. The exponent step `8 * n ==
   8 + 8 * (n - 1)` is linear, but left inside the `pow2` argument it makes
   `pow2_plus` a search rather than a rewrite. *)
let pow2_step (n: nat { n > 0 })
  : Lemma (pow2 (8 * n) == 256 * pow2 (8 * (n - 1)))
  = assert_norm (pow2 8 == 256);
    assert (8 * n == 8 + 8 * (n - 1));
    M.pow2_plus 8 (8 * (n - 1))

#push-options "--z3rlimit 30 --fuel 1 --ifuel 1"
let rec decode_le_encode (n: nat) (p: prov) (x: nat)
  : Lemma (ensures decode_le (encode LittleEndian n p x) == Some (x % pow2 (8 * n)))
          (decreases n)
  = if n = 0 then assert_norm (pow2 (8 * 0) == 1)
    else begin
      encode_head n p x;
      encode_tail n p x;
      decode_le_encode (n - 1) p (x / 256);
      pow2_step n;
      mod_split x (pow2 (8 * (n - 1)))
    end
#pop-options

let decode_encode (bo: byte_order) (n: nat) (p: prov) (x: nat)
  : Lemma (decode bo (encode bo n p x) == Some (x % pow2 (8 * n)))
  = match bo with
    | LittleEndian -> decode_le_encode n p x
    | BigEndian -> encode_rev n p x; decode_le_encode n p x

let decode_encode_exact (bo: byte_order) (n: nat) (p: prov) (x: nat { x < pow2 (8 * n) })
  : Lemma (decode bo (encode bo n p x) == Some x)
  = decode_encode bo n p x;
    M.small_mod x (pow2 (8 * n))

(* `encode` is injective in the value, which is what gives the scalar typed
   points-to predicates their agreement lemma. It is *not* injective in the
   provenance-erased sense: two encodings differing only in provenance are
   different byte ranges, which is exactly what we want, since a stored pointer
   and an integer with the same bit pattern are not interchangeable. *)
let encode_injective (bo: byte_order) (n: nat) (p: prov) (x y: nat)
  : Lemma (requires x < pow2 (8 * n) /\ y < pow2 (8 * n) /\ encode bo n p x == encode bo n p y)
          (ensures  x == y)
  = decode_encode_exact bo n p x;
    decode_encode_exact bo n p y

(* Zero is all-zero bytes in either order. `Pulse.Lib.C.Palow.Scalar` states
   this at the target's order as `encode_zero`, which is the name `calloc` and
   `memset` proofs use; this is the same fact for an order given explicitly. *)
let byte_at_zero (k: nat) : Lemma (byte_at None 0 k == zero_byte) =
  M.small_div 0 (pow2 (8 * k))

let encode_zero_in (bo: byte_order) (n: nat) : Lemma (encode bo n None 0 == zeroed n) =
  let aux (i: nat { i < n }) : Lemma (get (encode bo n None 0) i == get (zeroed n) i) =
    byte_at_zero (significance bo n i)
  in
  Classical.forall_intro aux;
  bytes_ext (encode bo n None 0) (zeroed n)

(* ---------------------------------------------------------------------------
   Surjectivity: initialised bytes of one provenance encode the value they
   decode to, in either order. `decode_encode` reads a value back out of its
   encoding; this is the converse, and it is what lets a typed view be claimed
   over bytes nobody has named a value for -- an ELF header in a guest image, a
   table the firmware left in memory. *)

#push-options "--z3rlimit 40 --fuel 1 --ifuel 1"
let rec decode_le_bound (b: bytes)
  : Lemma (requires initialized b)
          (ensures  Some? (decode_le b) /\ Some?.v (decode_le b) < pow2 (8 * len b))
          (decreases (len b))
  = if len b = 0 then assert_norm (pow2 (8 * 0) == 1)
    else begin
      decode_le_bound (slice b 1 (len b));
      pow2_step (len b)
    end

(* Kept out of `encode_decode_le`: in that context, with the induction
   hypothesis and the arithmetic below, even `i - 1 >= 0` is a search. *)
let head_tail_ext (e b: bytes)
  : Lemma (requires len e == len b /\ len b > 0 /\ get e 0 == get b 0 /\
                    slice e 1 (len e) == slice b 1 (len b))
          (ensures  e == b)
  = let n = len b in
    let aux (i: nat { i < n }) : Lemma (get e i == get b i) =
      if i = 0 then ()
      else begin
        Seq.lemma_index_slice e 1 n (i - 1);
        Seq.lemma_index_slice b 1 n (i - 1)
      end
    in
    Classical.forall_intro aux;
    bytes_ext e b

let rec encode_decode_le (p: prov) (b: bytes)
  : Lemma (requires initialized b /\ has_prov p b)
          (ensures  Some? (decode_le b) /\
                    encode LittleEndian (len b) p (Some?.v (decode_le b)) == b)
          (decreases (len b))
  = decode_le_bound b;
    let n = len b in
    if n = 0 then bytes_ext (encode LittleEndian 0 p 0) b
    else begin
      let t = slice b 1 n in
      encode_decode_le p t;
      let r = Some?.v (decode_le t) in
      let v = U8.v (Some?.v (get b 0).value) in
      let x = v + 256 * r in
      assert (decode_le b == Some x);
      encode_head n p x;
      M.lemma_mod_plus v r 256;
      M.small_mod v 256;
      assert (x % 256 == v);
      M.lemma_div_plus v r 256;
      M.small_div v 256;
      assert (x / 256 == r);
      encode_tail n p x;
      let e = encode LittleEndian n p x in
      assert (slice e 1 n == t);
      assert (get e 0 == get b 0);
      head_tail_ext e b
    end
#pop-options

let encode_decode (bo: byte_order) (p: prov) (b: bytes)
  : Lemma (requires initialized b /\ has_prov p b)
          (ensures  Some? (decode bo b) /\
                    Some?.v (decode bo b) < pow2 (8 * len b) /\
                    encode bo (len b) p (Some?.v (decode bo b)) == b)
  = match bo with
    | LittleEndian -> decode_le_bound b; encode_decode_le p b
    | BigEndian ->
      rev_initialized p b;
      decode_le_bound (rev b);
      encode_decode_le p (rev b);
      encode_be_as_rev (len b) p (Some?.v (decode_le (rev b)));
      rev_involutive b

(* The value a range of bytes holds, as a total function: what each scalar
   type's `_of_bytes` reads. Bytes that do not hold a value -- some of them
   uninitialised -- read as 0, and nothing can be concluded from that,
   because the lemmas below only speak about initialised ranges. *)
let decode_nat (bo: byte_order) (b: bytes) : nat =
  match decode bo b with
  | Some v -> v
  | None -> 0

(* The form every scalar's `_of_bytes_repr` uses: an `n`-byte range of one
   provenance is the encoding of what it decodes to, and that value is in
   range for an `n`-byte type, so reducing it modulo `pow2 (8 * n)` -- which is
   how `_of_bytes` makes it fit the F* type -- changes nothing. *)
let encode_decode_nat (bo: byte_order) (p: prov) (n: nat) (b: bytes)
  : Lemma (requires len b == n /\ initialized b /\ has_prov p b)
          (ensures  decode_nat bo b < pow2 (8 * n) /\
                    decode_nat bo b % pow2 (8 * n) == decode_nat bo b /\
                    encode bo n p (decode_nat bo b) == b)
  = encode_decode bo p b;
    M.small_mod (decode_nat bo b) (pow2 (8 * n))

(* ---------------------------------------------------------------------------
   Signed integers

   C leaves the signed representation implementation-defined, but every target
   PAL supports uses two's complement, and C23 mandates it. So a signed value
   is encoded as its non-negative residue: the same `encode` as an unsigned
   value of the same width, applied to `to_bits`.

   `to_bits` is stated on the bit width rather than the byte count because that
   is where the asymmetry of the signed range lives, and it carries the range
   through in its result type so that `encode` can be applied without a side
   condition at every use. *)
let to_bits (w: pos) (x: int { -(pow2 (w - 1)) <= x /\ x < pow2 (w - 1) })
  : n:nat { n < pow2 w }
  = M.pow2_double_sum (w - 1);
    if x < 0 then x + pow2 w else x

let to_bits_injective (w: pos)
                      (x: int { -(pow2 (w - 1)) <= x /\ x < pow2 (w - 1) })
                      (y: int { -(pow2 (w - 1)) <= y /\ y < pow2 (w - 1) })
  : Lemma (requires to_bits w x == to_bits w y)
          (ensures  x == y)
  = M.pow2_double_sum (w - 1)

(* The way back: the signed value whose two's-complement residue is `n`. It is
   what a signed scalar's `_of_bytes` applies to the bits it decodes, and
   `to_bits_of_bits` is the fact that makes the result represent those bits. *)
let of_bits (w: pos) (n: nat { n < pow2 w })
  : x:int { -(pow2 (w - 1)) <= x /\ x < pow2 (w - 1) }
  = M.pow2_double_sum (w - 1);
    if n < pow2 (w - 1) then n else n - pow2 w

let to_bits_of_bits (w: pos) (n: nat { n < pow2 w })
  : Lemma (to_bits w (of_bits w n) == n)
  = M.pow2_double_sum (w - 1)
