#include "pal.h"
#include <stdint.h>

// Example of how to replace the autogenerated pred for typedefs with
// some custom invariants.
_refine(_inline_pulse (exists* (v : Int32.t). Pulse.Lib.Reference.pts_to $(this.y) $(this.x)))
_plain
typedef struct foo{
    int x;
    int* y;
}foo;
