name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install clang
      run: |
        wget -O /tmp/llvm.sh https://apt.llvm.org/llvm.sh
        chmod +x /tmp/llvm.sh
        sudo /tmp/llvm.sh 20
        rm -f /tmp/llvm.sh
        sudo apt update
        sudo apt install -y clang-20 libclang-cpp20-dev g++ clang-tools-20 libclang-20-dev

    - name: Install F*
      run: ./opt/install-fstar.sh --link-dir /usr/local/bin