#include "pal.h"

// Custom invariants (`_refine`, `_plain`, ...) written directly on a tag-only
// `struct foo { ... };` declaration, i.e. without going through a typedef.
// PAL parses the record declaration's attributes once and stores the resulting
// refined self type on the struct definition. Every use of `struct foo` reuses
// that parsed type, exactly as every typedef use reuses its stored body (see
// test/refine_typedef_pred and test/array_test for the typedef spelling).
//
// Note on placement: the attribute has to be written *after* the `struct`
// keyword. Writing it before the keyword makes clang warn that the attribute is
// ignored ("place it after \"struct\" to apply attribute to type declaration"),
// and the annotation is then dropped.

// A pure refinement: the array field always has exactly 32 elements. This is
// the same invariant as `b32_struct` in test/array_test, written here on the
// struct declaration instead of on a typedef. The length equation makes
// `a.x[10]` provably in bounds.
struct _refine(this.x._length == 32) b32_struct {
  _array unsigned char *x;
};

void b32_arr(struct b32_struct a)
  _ensures(a.x[10] == 67)
{
  a.x[10] = 67;
}

// The same refinement, but reached through a pointer to the struct rather than
// a by-value struct, so the invariant has to survive a field access through a
// reference.
void set_elem(struct b32_struct *p, unsigned char v)
  _ensures(p->x[3] == v)
{
  p->x[3] = v;
}

// Multiple mentions of the same struct reuse the one parsed refinement.
unsigned char copy_elem(struct b32_struct src, struct b32_struct dst)
  _ensures(dst.x[4] == src.x[4])
{
  dst.x[4] = src.x[4];
  return dst.x[4];
}

// A refined struct used as another struct's field is resolved through the same
// cached definition while constructing the outer struct's predicate.
struct wrapper {
  struct b32_struct inner;
};

// Forward declarations remain lightweight name declarations; the complete
// definition owns the one parsed refinement used by later references.
struct forward_refined;

struct _refine(this.x > 0) forward_refined {
  int x;
};

int read_positive(struct forward_refined s)
  _ensures(return > 0)
{
  return s.x;
}

// A separating-logic refinement that replaces the autogenerated predicate
// entirely: `_plain` suppresses the default ownership and `_refine` states that
// the struct always owns `*y`, whose contents equal the `x` field. This mirrors
// test/refine_typedef_pred, which is the same declaration behind a typedef.
struct _refine(_inline_pulse (Pulse.Lib.Reference.pts_to $(this.y) $(this.x)))
    _plain selfref {
  int x;
  int *y;
};

int read_via_y(struct selfref s)
  _ensures(return == s.x)
{
  return *s.y;
}
